### ISSUE TITLE
Error during compilation in pip

### ISSUE THREAD

**Issue by dtrckd** [charanpald/sppy#7]
Hi,
After getting libomp 3.7 and libeigen 3.3 dev packages, the pip install sppy return a lot of errors.

Any advice ?

Thanks for this project.

**Comment by charanpald** [comment]
Hi,
I'm not sure without details of the error. Perhaps try installing the package using: 

```
python setup.py install 
```

first as pip can run into problems. If that still doesn't work, just send the error message you get. 

Charanpal

**Comment by dtrckd** [comment]
Ok, 

I got error in both case setup.py and pip building. It seems to deals with the libeigen3. I build with python2.7...

I join the output of the install...
[error_out.txt](https://github.com/charanpald/sppy/files/72433/error_out.txt)

**Comment by charanpald** [comment]
It's really hard to understand what is happening from the error message. Can you send a few details of your system (numpy version, eigen, OS, C++ compiler) and I will try to replicate the problem on my machine. The only thing I can think of at the moment is an old version of Eigen (it was tested with version 3.2). You can try switching to 3.2 if this is not what you currently have.

**Comment by dtrckd** [comment]
I downgraded libeigen to 3.2, and it compile then...
Thanks for the help.
